export { default as DialogDelete } from '../../components/DialogDelete.vue'
export { default as ImageUpload } from '../../components/ImageUpload.vue'
export { default as Logo } from '../../components/Logo.vue'
export { default as VuetifyLogo } from '../../components/VuetifyLogo.vue'
export { default as DialogLoader } from '../../components/dialog-loader.vue'
export { default as FebButton } from '../../components/febButton.vue'
export { default as FebButtonWork } from '../../components/febButtonWork.vue'
export { default as BarChartDashBranch } from '../../components/BarChartDash/BarChartDashBranch.vue'
export { default as BarChartDashCar } from '../../components/BarChartDash/BarChartDashCar.vue'
export { default as BarChartDashSale } from '../../components/BarChartDash/BarChartDashSale.vue'
export { default as BarChartDashSaleByBranch } from '../../components/BarChartDash/BarChartDashSaleByBranch.vue'
export { default as BarChartDashTopCarSerie } from '../../components/BarChartDash/BarChartDashTopCarSerie.vue'
export { default as BarChartDashVisit } from '../../components/BarChartDash/BarChartDashVisit.vue'
export { default as BarChartDashVisitCarDown } from '../../components/BarChartDash/BarChartDashVisitCarDown.vue'
export { default as BarChartDashVisitCarModel } from '../../components/BarChartDash/BarChartDashVisitCarModel.vue'
export { default as BarChartDashVisitCarSerie } from '../../components/BarChartDash/BarChartDashVisitCarSerie.vue'
export { default as BarChartDashVisitCarSlacken } from '../../components/BarChartDash/BarChartDashVisitCarSlacken.vue'
export { default as BarChartDashVisitCarType } from '../../components/BarChartDash/BarChartDashVisitCarType.vue'
export { default as BarChartBranch } from '../../components/BarChart/BarChartBranch.vue'
export { default as BarChartCar } from '../../components/BarChart/BarChartCar.vue'
export { default as BarChartPriceCar } from '../../components/BarChart/BarChartPriceCar.vue'
export { default as BarChartSale } from '../../components/BarChart/BarChartSale.vue'
export { default as BarChartSaleCarByBranch } from '../../components/BarChart/BarChartSaleCarByBranch.vue'
export { default as BarChartTopCars } from '../../components/BarChart/BarChartTopCars.vue'
export { default as BarChartVisit } from '../../components/BarChart/BarChartVisit.vue'
export { default as BarChartVisitCar } from '../../components/BarChart/BarChartVisitCar.vue'
export { default as BarChartVisitLine } from '../../components/BarChart/BarChartVisitLine.vue'
export { default as DashboardComInsurances } from '../../components/Dashboard/ComInsurances.vue'
export { default as DashboardComInventoryCar } from '../../components/Dashboard/ComInventoryCar.vue'
export { default as DashboardComRegis } from '../../components/Dashboard/ComRegis.vue'
export { default as DashboardComWorkStatus } from '../../components/Dashboard/ComWorkStatus.vue'
export { default as DateSelect } from '../../components/DateSelect/dateSelect.vue'
export { default as DateSelect2 } from '../../components/DateSelect/dateSelect2.vue'
export { default as DateSelectMonth } from '../../components/DateSelect/dateSelectMonth.vue'
export { default as DateSelectMonthAll } from '../../components/DateSelect/dateSelectMonthAll.vue'
export { default as ChartLine } from '../../components/Chart/Line.vue'
export { default as DoughnutChartCarType } from '../../components/DoughnutChartDash/DoughnutChartCarType.vue'
export { default as DoughnutChartDashBranchCar } from '../../components/DoughnutChartDash/DoughnutChartDashBranchCar.vue'
export { default as DoughnutChartDashSale } from '../../components/DoughnutChartDash/DoughnutChartDashSale.vue'
export { default as DoughnutChartBranch } from '../../components/DoughnutChart/DoughnutChartBranch.vue'
export { default as DoughnutChartCar } from '../../components/DoughnutChart/DoughnutChartCar.vue'
export { default as DoughnutChartUser } from '../../components/DoughnutChart/DoughnutChartUser.vue'
export { default as DialogCardRequestLog } from '../../components/dialog/cardRequestLog.vue'
export { default as DialogAddIncome } from '../../components/dialog/dialogAdd_income.vue'
export { default as DialogAddLowCars } from '../../components/dialog/dialogAdd_lowCars.vue'
export { default as DialogAddMoney } from '../../components/dialog/dialogAdd_money.vue'
export { default as DialogAddOutlay } from '../../components/dialog/dialogAdd_outlay.vue'
export { default as DialogAddOutlaySmall } from '../../components/dialog/dialogAdd_outlay_small.vue'
export { default as DialogAmountDown } from '../../components/dialog/dialogAmount_down.vue'
export { default as DialogAmountSlacken } from '../../components/dialog/dialogAmount_slacken.vue'
export { default as DialogAmphure } from '../../components/dialog/dialogAmphure.vue'
export { default as DialogAppointment } from '../../components/dialog/dialogAppointment.vue'
export { default as DialogAppointmentBank } from '../../components/dialog/dialogAppointmentBank.vue'
export { default as DialogBank } from '../../components/dialog/dialogBank.vue'
export { default as DialogBankBranch } from '../../components/dialog/dialogBank_branch.vue'
export { default as DialogBooking } from '../../components/dialog/dialogBooking.vue'
export { default as DialogBranch } from '../../components/dialog/dialogBranch.vue'
export { default as DialogBranchTeam } from '../../components/dialog/dialogBranchTeam.vue'
export { default as DialogCarLift } from '../../components/dialog/dialogCarLift.vue'
export { default as DialogCarModel } from '../../components/dialog/dialogCarModel.vue'
export { default as DialogCarPart } from '../../components/dialog/dialogCarPart.vue'
export { default as DialogCarPartType } from '../../components/dialog/dialogCarPartType.vue'
export { default as DialogCarSerieSub } from '../../components/dialog/dialogCarSerieSub.vue'
export { default as DialogCarSeries } from '../../components/dialog/dialogCarSeries.vue'
export { default as DialogCarType } from '../../components/dialog/dialogCarType.vue'
export { default as DialogColor } from '../../components/dialog/dialogColor.vue'
export { default as DialogCommission } from '../../components/dialog/dialogCommission.vue'
export { default as DialogContract } from '../../components/dialog/dialogContract.vue'
export { default as DialogCustomer } from '../../components/dialog/dialogCustomer.vue'
export { default as DialogCustomerDetail } from '../../components/dialog/dialogCustomer_detail.vue'
export { default as DialogCustomerVisit } from '../../components/dialog/dialogCustomer_visit.vue'
export { default as DialogDistricts } from '../../components/dialog/dialogDistricts.vue'
export { default as DialogFileCar } from '../../components/dialog/dialogFileCar.vue'
export { default as DialogFinancialFullOld } from '../../components/dialog/dialogFinancial-Full-old.vue'
export { default as DialogFinancial } from '../../components/dialog/dialogFinancial.vue'
export { default as DialogFuel } from '../../components/dialog/dialogFuel.vue'
export { default as DialogGeographie } from '../../components/dialog/dialogGeographie.vue'
export { default as DialogImage } from '../../components/dialog/dialogImage.vue'
export { default as DialogImageCar } from '../../components/dialog/dialogImage_car.vue'
export { default as DialogInstallment } from '../../components/dialog/dialogInstallment.vue'
export { default as DialogInstallmentHistory } from '../../components/dialog/dialogInstallmentHistory.vue'
export { default as DialogInstallmentPayment } from '../../components/dialog/dialogInstallmentPayment.vue'
export { default as DialogInsurCertificate } from '../../components/dialog/dialogInsurCertificate.vue'
export { default as DialogInsurance } from '../../components/dialog/dialogInsurance.vue'
export { default as DialogInsurancesList } from '../../components/dialog/dialogInsurancesList.vue'
export { default as DialogJobDetail } from '../../components/dialog/dialogJobDetail.vue'
export { default as DialogJobTechnician } from '../../components/dialog/dialogJobTechnician.vue'
export { default as DialogLowCars } from '../../components/dialog/dialogLowCars.vue'
export { default as DialogMiddlePrice } from '../../components/dialog/dialogMiddle_price.vue'
export { default as DialogMiniCar } from '../../components/dialog/dialogMini_car.vue'
export { default as DialogMiniUser } from '../../components/dialog/dialogMini_user.vue'
export { default as DialogNegotiation } from '../../components/dialog/dialogNegotiation.vue'
export { default as DialogNote } from '../../components/dialog/dialogNote.vue'
export { default as DialogPartnerCar } from '../../components/dialog/dialogPartnerCar.vue'
export { default as DialogPartnerCompany } from '../../components/dialog/dialogPartnerCompany.vue'
export { default as DialogPartnerTechnician } from '../../components/dialog/dialogPartner_technician.vue'
export { default as DialogPathnerJobTechnician } from '../../components/dialog/dialogPathnerJobTechnician.vue'
export { default as DialogPreApprove } from '../../components/dialog/dialogPreApprove.vue'
export { default as DialogPriceRecord } from '../../components/dialog/dialogPriceRecord.vue'
export { default as DialogPromotion } from '../../components/dialog/dialogPromotion.vue'
export { default as DialogProvince } from '../../components/dialog/dialogProvince.vue'
export { default as DialogPurchaseCar } from '../../components/dialog/dialogPurchaseCar.vue'
export { default as DialogPurchasePart } from '../../components/dialog/dialogPurchasePart.vue'
export { default as DialogReceiveDown } from '../../components/dialog/dialogReceiveDown.vue'
export { default as DialogReceivingMoney } from '../../components/dialog/dialogReceivingMoney.vue'
export { default as DialogRepairList } from '../../components/dialog/dialogRepairList.vue'
export { default as DialogRepairPrice } from '../../components/dialog/dialogRepairPrice.vue'
export { default as DialogRequestLog } from '../../components/dialog/dialogRequestLog.vue'
export { default as DialogRequestUpdate } from '../../components/dialog/dialogRequestUpdate.vue'
export { default as DialogRequestWithdraw } from '../../components/dialog/dialogRequestWithdraw.vue'
export { default as DialogSearchTerm } from '../../components/dialog/dialogSearch_term.vue'
export { default as DialogStockCar } from '../../components/dialog/dialogStockCar.vue'
export { default as DialogStockPart } from '../../components/dialog/dialogStockPart.vue'
export { default as DialogUnit } from '../../components/dialog/dialogUnit.vue'
export { default as DialogUser } from '../../components/dialog/dialogUser.vue'
export { default as DialogUserGroup } from '../../components/dialog/dialogUserGroup.vue'
export { default as DialogUserLine } from '../../components/dialog/dialogUserLine.vue'
export { default as DialogUserTeam } from '../../components/dialog/dialogUserTeam.vue'
export { default as DialogWithdrawPart } from '../../components/dialog/dialogWithdrawPart.vue'
export { default as DialogWork } from '../../components/dialog/dialogWork.vue'
export { default as DialogDrawerFile } from '../../components/dialog/drawerFile.vue'
export { default as DialogDrawerRequestLog } from '../../components/dialog/drawerRequestLog.vue'
export { default as MobileDialogBooking } from '../../components/mobile/dialogBooking.vue'
export { default as MobileDialogInsurCertificate } from '../../components/mobile/dialogInsurCertificate.vue'
export { default as MobileDialogReceiveDown } from '../../components/mobile/dialogReceiveDown.vue'
export { default as SelectDropDownAmphure } from '../../components/selectDropDown/selectDropDownAmphure.vue'
export { default as SelectAddCarModel } from '../../components/selectAdd/selectAddCarModel.vue'
export { default as SelectAddCarPart } from '../../components/selectAdd/selectAddCarPart.vue'
export { default as SelectAddCarPartType } from '../../components/selectAdd/selectAddCarPartType.vue'
export { default as SelectAddCarSerie } from '../../components/selectAdd/selectAddCarSerie.vue'
export { default as SelectAddCarSerieSub } from '../../components/selectAdd/selectAddCarSerieSub.vue'
export { default as SelectAddCarType } from '../../components/selectAdd/selectAddCarType.vue'
export { default as SelectAddCustomer } from '../../components/selectAdd/selectAddCustomer.vue'
export { default as SelectAddPartnerCar } from '../../components/selectAdd/selectAddPartnerCar.vue'
export { default as SelectAddPartnerTechnician } from '../../components/selectAdd/selectAddPartner_technician.vue'
export { default as SelectAddSearchTerm } from '../../components/selectAdd/selectAddSearch_term.vue'
export { default as SelectAddUnit } from '../../components/selectAdd/selectAddUnit.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
